/* Generated By:JavaCC: Do not edit this line. compTreeConstants.java Version 5.0 */
public interface compTreeConstants
{
  public int JJTINICIO = 0;
  public int JJTIMPORTACION = 1;
  public int JJTBLOQUE = 2;
  public int JJTDECLARACION_VARIABLES_GLOBALES = 3;
  public int JJTMAIN = 4;
  public int JJTVARIABLESLOCALES = 5;
  public int JJTVARIABLESASIGNACION = 6;
  public int JJTVOID = 7;
  public int JJTSENTENCIAS = 8;
  public int JJTIF = 9;
  public int JJTELSEIF = 10;
  public int JJTCOMPARACIONDECOMPARACIONES = 11;
  public int JJTCOMPARACIONES = 12;
  public int JJTVALOR = 13;
  public int JJTEXPRESION = 14;
  public int JJTOPLOGI = 15;
  public int JJTOPARIT = 16;
  public int JJTTIPODATO = 17;
  public int JJTFOR = 18;
  public int JJTDECLARARVARIABLE = 19;
  public int JJTDO = 20;
  public int JJTWHILE = 21;
  public int JJTSENTENCIAASIGNACION = 22;
  public int JJTTIPOSASIGNACIONES = 23;
  public int JJTWRITE = 24;
  public int JJTREAD = 25;
  public int JJTSWITCH = 26;


  public String[] jjtNodeName = {
    "Inicio",
    "Importacion",
    "Bloque",
    "declaracion_variables_globales",
    "Main",
    "VariablesLocales",
    "VariablesAsignacion",
    "void",
    "Sentencias",
    "IF",
    "ELSEIF",
    "comparaciondecomparaciones",
    "Comparaciones",
    "Valor",
    "Expresion",
    "oplogi",
    "oparit",
    "tipodato",
    "FOR",
    "declararvariable",
    "DO",
    "WHILE",
    "SentenciaAsignacion",
    "TiposAsignaciones",
    "WRITE",
    "READ",
    "SWITCH",
  };
}
/* JavaCC - OriginalChecksum=94680bde3511b4212b640ff99f6534ba (do not edit this line) */
